### ISSUE TITLE
Suggestion for defining multiple attributes at once

### ISSUE THREAD

**Issue by tobyink** [bbrtj/perl-mooish-attributebuilder#1]
One possibility is to allow sprintf-like strings as method names:

```perl
has [ 'user_agent', 'secure_user_agent' ] => (
  is        => 'ro',
  isa       => Object,
  predicate => 'has_%s',
  handles   => { '%s_get' => 'get', '%s_post' => 'post' },
);
```

This would be equivalent to:

```perl
has user_agent => (
  is        => 'ro',
  isa       => Object,
  predicate => 'has_user_agent',
  handles   => { 'user_agent_get' => 'get', 'user_agent_post' => 'post' },
);

has secure_user_agent => (
  is        => 'ro',
  isa       => Object,
  predicate => 'has_secure_user_agent',
  handles   => { 'secure_user_agent_get' => 'get', 'secure_user_agent_post' => 'post' },
);
```

**Comment by bbrtj** [comment]
Hello there,

thank you for the suggestion, but it doesn't seem this works with base Moo:

```
use Moo;

has ['test', 'test2'] => (
	is => 'ro',
	writer => 'set_%s',
);
```

Mooish::AttributeBuilder is just a filter for `has` parameters, so it can't do anything that (a single) `has` can't. Plus the goal is to be compatible with at least base Moo, Moose and Mouse, so it can't take advantage of any plugin targeting specifically one of those.

It might be that I misunderstood what you're suggesting, in which case could you elaborate a bit on how it could be implemented?

**Comment by tobyink** [comment]
Hmm, true. It doesn't work without also wrapping `has`.
